version: 2
jobs:
  build:
    working_directory: /go/src/github.com/facebookincubator/fbender
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: go get -t -v ./...
      - run:
          name: Lint
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
            go get -u golang.org/x/lint/golint
            golangci-lint run
            golint -set_exit_status
